### ISSUE TITLE
Unable to locate collection tripplite.poweralert

### ISSUE THREAD

**Issue by problemsolver-jpg** [jeisenbath/ansible-collection-tripplite-poweralert#1]
Using given examples and syntax ansible returns error:

{"msg": "error processing module_util ansible_collections.tripplite.poweralert.plugins.module_utils.padm.Tripplite loading redirected collection tripplite.poweralert: unable to locate collection tripplite.poweralert"}

**Comment by jeisenbath** [comment]
ah sorry I just started updating this module to upload it to galaxy, and changed it to my own namespace without changing the examples.

The fqcn should be jeisenbath.tripplite instead of tripplite.poweralert, I'll correct those examples shortly. Thanks!

**Comment by problemsolver-jpg** [comment]
The error was received using the collection as listed below.
 
  tasks:
  - name: Get API info from devices!
    jeisenbath.tripplite.padm_api:
      <<: *tripplite_info
      uri: /api/devices
      method: get
    register: tripplite_info
    delegate_to: localhost

**Comment by jeisenbath** [comment]
Pushed 1.0.1 to bugfix, I forgot to update the import paths also after namespace change.
